env:
  SERVICE_PATH: services/dozzle

name: Deploy Dozzle to My Server

run-name: ${{ github.actor }} is deploying to My Server ðŸš€

on:
  push:
    branches:
      - main
    paths:
      - services/dozzle/**
      - .github/workflows/dozzle.yml
      - .github/actions/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup & encode SOPS
        uses: ./.github/actions/sops-decode
        with:
          filePath: ${{ env.SERVICE_PATH }}/users.yml

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          servicePath: ${{ env.SERVICE_PATH }}
